# INICIANDO LIBRERIAS

In [2]:
import pandas as pd
import numpy as np
import sys
import matplotlib.pyplot as plt

# Creando la ruta

In [3]:
ruta = "Data\All_Pokemon.csv"
df = pd.read_csv(ruta, index_col="Number")

df

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\Chaiguata 1\AppData\Local\Temp\ipykernel_11800\2886512139.py:1: SyntaxWarning: invalid escape sequence '\A'
  ruta = "Data\All_Pokemon.csv"

,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,Spe,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
Number,,,,,,,,,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,80,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,80,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,65,...,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898,Calyrex,Psychic,Grass,['Unnerve'],100,80,80,80,80,80,...,4.0,1.0,2.0,1.0,2.0,1.0,1.0,1.1,7.7,6.4
898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,50,...,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5
898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,150,...,1.0,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3
899,Alolan Raichu,Electric,Psychic,['Surge Surfer'],60,85,50,95,85,110,...,2.0,1.0,2.0,1.0,2.0,0.5,1.0,0.7,21.0,42.9
900,Kangaskhan,Normal,NaN,"['Early Bird', 'Inner Focus', 'Scrappy']",105,95,80,40,80,90,...,1.0,1.0,0.0,1.0,1.0,1.0,1.0,2.2,80.0,16.5

# INFORMACION GENERAL

In [5]:
info_de_df = df.info()
info_de_df

<class 'pandas.core.frame.DataFrame'>
Index: 1034 entries, 1 to 900
Data columns (total 43 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     1034 non-null   object
 1   Type 1                   1034 non-null   object
 2   Type 2                   549 non-null    object
 3   Abilities                1034 non-null   object
 4   HP                       1034 non-null   int64
 5   Att                      1034 non-null   int64
 6   Def                      1034 non-null   int64
 7   Spa                      1034 non-null   int64
 8   Spd                      1034 non-null   int64
 9   Spe                      1034 non-null   int64
 10  BST                      1034 non-null   int64
 11  Mean                     1034 non-null   float64
 12  Standard Deviation       1034 non-null   float64
 13  Generation               1034 non-null   float64
 14  Experience type          1034 non-null   object
 15  Experience to level 100  1034 non-null   int64
 16  Final Evolution          1034 non-null   float64
 17  Catch Rate               1034 non-null   int64
 18  Legendary                1034 non-null   float64
 19  Mega Evolution           1034 non-null   float64
 20  Alolan Form              1034 non-null   float64
 21  Galarian Form            1034 non-null   float64
 22  Against Normal           1034 non-null   float64
 23  Against Fire             1034 non-null   float64
 24  Against Water            1034 non-null   float64
 25  Against Electric         1034 non-null   float64
 26  Against Grass            1034 non-null   float64
 27  Against Ice              1034 non-null   float64
 28  Against Fighting         1034 non-null   float64
 29  Against Poison           1034 non-null   float64
 30  Against Ground           1034 non-null   float64
 31  Against Flying           1034 non-null   float64
 32  Against Psychic          1034 non-null   float64
 33  Against Bug              1034 non-null   float64
 34  Against Rock             1034 non-null   float64
 35  Against Ghost            1034 non-null   float64
 36  Against Dragon           1034 non-null   float64
 37  Against Dark             1034 non-null   float64
 38  Against Steel            1034 non-null   float64
 39  Against Fairy            1034 non-null   float64
 40  Height                   1034 non-null   float64
 41  Weight                   1034 non-null   float64
 42  BMI                      1034 non-null   float64
dtypes: float64(29), int64(9), object(5)
memory usage: 355.4+ KB

# INFORMACION ESTADISTICA RESUMIDA

In [8]:
Estadistica_df = df.describe()

Estadistica_df

,HP,Att,Def,Spa,Spd,Spe,BST,Mean,Standard Deviation,Generation,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
count,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,...,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000
mean,69.930368,80.544487,74.590909,72.908124,72.159574,68.609284,438.742747,73.123791,20.028863,4.431335,...,1.003143,1.239362,1.025629,0.974855,1.075677,0.991538,1.094052,1.287137,71.838491,136.528723
std,26.188367,32.514268,30.885981,32.764971,27.603097,30.225102,120.577842,20.096307,10.819824,2.265449,...,0.613302,0.698763,0.578387,0.377676,0.475708,0.511592,0.534657,1.390564,132.753724,3108.656552
min,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,175.000000,29.166667,0.000000,1.000000,...,0.250000,0.250000,0.000000,0.000000,0.250000,0.250000,0.250000,0.100000,0.100000,0.000000
25%,50.000000,55.250000,50.000000,50.000000,50.000000,45.000000,330.000000,55.000000,12.808683,3.000000,...,0.500000,1.000000,1.000000,1.000000,1.000000,0.500000,1.000000,0.600000,9.000000,18.600000
50%,67.000000,78.000000,70.000000,65.000000,70.000000,65.000000,460.000000,76.666667,18.531071,5.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,29.750000,28.350000
75%,83.000000,100.000000,90.000000,95.000000,90.000000,90.000000,515.000000,85.833333,24.830537,6.000000,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.600000,71.425000,42.200000
max,255.000000,190.000000,230.000000,194.000000,230.000000,200.000000,780.000000,130.000000,103.215659,8.000000,...,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,4.000000,20.000000,999.900000,99990.000000

# DUPLICADOS

In [10]:
duplicados = df.duplicated().sum()
if duplicados > 0:
    print(f"se encotraron {duplicados} Filas duplicadas")
    df.drop_duplicates(inplace=True)
else:
    print("no hay")

no hay